apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.ingressPort }}
      targetPort: {{ .Values.servicePort }}
